[package]
name = "r3_core"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "R3 RTOS core API definition (placeholder)"
keywords = ["r3"]
repository = "https://github.com/r3-os/r3"

[dependencies]
