[package]
name = "r3_core"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "R3 RTOS core API definition (placeholder)"
categories = ["embedded", "no-std"]
keywords = ["r3", "rtos"]
repository = "https://github.com/r3-os/r3"

[dependencies]
