#![feature(external_doc)] // `#[doc(include = ...)]`
#![feature(const_fn)]
#![feature(const_panic)]
#![feature(const_option)]
#![feature(decl_macro)]
#![feature(is_sorted)]
#![feature(asm)]
#![feature(cfg_target_has_atomic)]
#![feature(unsafe_block_in_unsafe_fn)] // `unsafe fn` doesn't imply `unsafe {}`
#![deny(unsafe_op_in_unsafe_fn)]
#![doc(include = "./lib.md")]
#![doc(include = "../../constance/src/common.md")]
#![no_std]

mod utils;

// Generated by `build.rs`. Defines `get_selected_kernel_tests_inner!`.
include!(concat!(env!("OUT_DIR"), "/selective_tests.rs"));

/// Kernel tests
pub mod kernel_tests {
    use constance::kernel::{InterruptNum, InterruptPriority};
    /// Instantiation parameters of a test case.
    ///
    /// This trait has two purposes: (1) It serves as an interface to a test driver.
    /// It provides methods to notify the test driver of test success or failure.
    /// (2) It provides runtime access to the `App` structure.
    pub trait Driver<App> {
        /// Get a reference to `App` of the current test case.
        fn app() -> &'static App;

        /// Signal to the test runner that a test has succeeded.
        fn success();

        /// Signal to the test runner that a test has failed.
        fn fail();

        /// The list of interrupt lines that can be used by test programs.
        ///
        ///  - The list can have an arbitrary number of elements. Some tests
        ///    will be silently skipped if it's not enough. There should be at
        ///    least two for all test cases to run.
        ///
        ///  - There must be no duplicates.
        ///
        ///  - The port must support [`enable_interrupt_line`],
        ///    [`disable_interrupt_line`], [`pend_interrupt_line`] for all of
        ///    the specified interrupt lines.
        ///
        /// [`enable_interrupt_line`]: constance::kernel::PortInterrupts::enable_interrupt_line
        /// [`disable_interrupt_line`]: constance::kernel::PortInterrupts::disable_interrupt_line
        /// [`pend_interrupt_line`]: constance::kernel::PortInterrupts::pend_interrupt_line
        const INTERRUPT_LINES: &'static [InterruptNum] = &[];

        /// A low priority value.
        ///
        /// Ignored if `INTERRUPT_LINES` is empty.
        ///
        /// Must be in range [`MANAGED_INTERRUPT_PRIORITY_RANGE`]
        ///
        /// [`MANAGED_INTERRUPT_PRIORITY_RANGE`]: constance::kernel::PortInterrupts::MANAGED_INTERRUPT_PRIORITY_RANGE
        const INTERRUPT_PRIORITY_LOW: InterruptPriority = 0;
        /// A high priority value.
        ///
        /// Ignored if `INTERRUPT_LINES` is empty.
        ///
        /// Must be in range [`MANAGED_INTERRUPT_PRIORITY_RANGE`]
        ///
        /// [`MANAGED_INTERRUPT_PRIORITY_RANGE`]: constance::kernel::PortInterrupts::MANAGED_INTERRUPT_PRIORITY_RANGE
        const INTERRUPT_PRIORITY_HIGH: InterruptPriority = 0;
    }

    macro_rules! define_kernel_tests {
        (
            [$dollar:tt] // get a `$` token
            $(
                // Test case definition
                (mod $name_ident:ident {}, $name_str:literal)
            ),*$(,)*
        ) => {
            $(
                /// [**Test Case**]
                #[cfg(any(
                    feature = "tests_all",
                    all(feature = "tests_selective", kernel_test = $name_str)
                ))]
                pub mod $name_ident;
            )*

            /// The names of kernel tests.
            pub const TEST_NAMES: &[&str] = &[
                $( $name_str ),*
            ];

            /// Invoke the specified macro with a description of all defined
            /// kernel test cases.
            ///
            /// Note that the tests might not be actually compiled unless the
            /// feature `tests_all` is enabled.
            ///
            /// # Example
            ///
            /// ```rust,ignore
            /// constance_test_suite::get_kernel_tests!(aaa::bbb!(prefix));
            /// ```
            ///
            /// This expands to something like this:
            ///
            /// ```rust,ignore
            /// aaa::bbb!(
            ///     prefix
            ///     { path: constance_test_suite::test1, name_ident: test1, name_str: "test1", },
            ///     { path: constance_test_suite::test2, name_ident: test2, name_str: "test2", },
            /// );
            /// ```
            ///
            #[macro_export]
            macro_rules! get_kernel_tests {
                (
                    // Callback macro
                    $path:ident$dollar(::$path_sub:ident)* ! (
                        // Prefix of the callback parameter
                        $dollar($prefix:tt)*
                    )
                ) => {
                    $path$dollar($path_sub)* ! (
                        // Prefix
                        $dollar($prefix)*
                        $(
                            // The test info
                            {
                                path: $crate::kernel_tests::$name_ident,
                                name_ident: $name_ident,
                                name_str: $name_str,
                            },
                        )*
                    );
                };
            }
        };
    }

    define_kernel_tests! {
        [$]
        (mod basic {}, "basic"),
        (mod compute_atomics_round_robin {}, "compute_atomics_round_robin"),
        (mod compute_round_robin {}, "compute_round_robin"),
        (mod cpu_lock {}, "cpu_lock"),
        (mod event_group_interrupt {}, "event_group_interrupt"),
        (mod event_group_misc {}, "event_group_misc"),
        (mod event_group_order_fifo {}, "event_group_order_fifo"),
        (mod event_group_order_task_priority {}, "event_group_order_task_priority"),
        (mod event_group_poll {}, "event_group_poll"),
        (mod event_group_reorder_task_priority {}, "event_group_reorder_task_priority"),
        (mod event_group_set_and_dispatch {}, "event_group_set_and_dispatch"),
        (mod event_group_timeout {}, "event_group_timeout"),
        (mod event_group_wait_types {}, "event_group_wait_types"),
        (mod interrupt_disallowed_services {}, "interrupt_disallowed_services"),
        (mod interrupt_during_boot {}, "interrupt_during_boot"),
        (mod interrupt_handler_priority {}, "interrupt_handler_priority"),
        (mod interrupt_misc {}, "interrupt_misc"),
        (mod interrupt_priority {}, "interrupt_priority"),
        (mod interrupt_task_activate {}, "interrupt_task_activate"),
        (mod priority_boost {}, "priority_boost"),
        (mod semaphore_interrupt_handler {}, "semaphore_interrupt_handler"),
        (mod semaphore_misc {}, "semaphore_misc"),
        (mod semaphore_signal_and_dispatch {}, "semaphore_signal_and_dispatch"),
        (mod semaphore_timeout {}, "semaphore_timeout"),
        (mod startup_hook_disallowed_services {}, "startup_hook_disallowed_services"),
        (mod startup_hook_pend_interrupt {}, "startup_hook_pend_interrupt"),
        (mod startup_hook_priority {}, "startup_hook_priority"),
        (mod task_activate_and_dispatch {}, "task_activate_and_dispatch"),
        (mod task_activate_and_do_not_dispatch {}, "task_activate_and_do_not_dispatch"),
        (mod task_cpu_lock_reset {}, "task_cpu_lock_reset"),
        (mod task_misc {}, "task_misc"),
        (mod task_park {}, "task_park"),
        (mod task_park_priority_boost {}, "task_park_priority_boost"),
        (mod task_park_reset {}, "task_park_reset"),
        (mod task_priority_boost_reset {}, "task_priority_boost_reset"),
        (mod task_priority_reset {}, "task_priority_reset"),
        (mod task_queue_fifo {}, "task_queue_fifo"),
        (mod task_set_priority {}, "task_set_priority"),
        (mod task_take_interrupt_at_return {}, "task_take_interrupt_at_return"),
        (mod time_adjust_event {}, "time_adjust_event"),
        (mod time_adjust_limits {}, "time_adjust_limits"),
        (mod time_misc {}, "time_misc"),
        (mod time_set_event {}, "time_set_event"),
        (mod time_stress {}, "time_stress"),
        (mod timer_misc {}, "timer_misc"),
        (mod timer_overdue {}, "timer_overdue"),
        (mod timer_periodic {}, "timer_periodic"),
        (mod timer_stop {}, "timer_stop"),
        (mod timer_zero_period {}, "timer_zero_period"),
    }

    /// Invoke the specified macro with a description of test cases
    /// selected by `CONSTANCE_TEST`.
    ///
    /// Note that the tests might not be actually compiled unless the
    /// feature `tests_selective` is enabled.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// constance_test_suite::get_selected_kernel_tests!(aaa::bbb!(prefix));
    /// ```
    ///
    /// If there's an environment variable `CONSTANCE_TEST=kernel_test::test1`,
    /// this expands to:
    ///
    /// ```rust,ignore
    /// aaa::bbb!(
    ///     prefix
    ///     { path: constance_test_suite::test1, name_ident: test1, name_str: "test1", },
    /// );
    /// ```
    ///
    #[macro_export]
    macro_rules! get_selected_kernel_tests {
        (
            // Callback macro
            $path:ident$(::$path_sub:ident)* ! (
                // Prefix of the callback parameter
                $($prefix:tt)*
            )
        ) => {
            // Forward to `get_selected_kernel_tests_inner!`
            $crate::get_selected_kernel_tests_inner!(
                ( $path $(::$path_sub)* ), ( $($prefix)* )
            );
        };
    }
}

/// Kernel benchmarks
pub mod kernel_benchmarks {
    use constance::kernel::{InterruptNum, InterruptPriority};

    /// Instantiation parameters of a test case.
    ///
    /// This trait has two purposes: (1) It serves as an interface to a test driver.
    /// It provides methods to notify the test driver of test success or failure.
    /// (2) It provides runtime access to the `App` structure.
    pub trait Driver<App> {
        /// Get a reference to `App` of the current test case.
        fn app() -> &'static App;

        /// Signal to the test runner that a test has succeeded.
        fn success();

        /// Get the current time for performance measurement.
        fn performance_time() -> u32;

        /// Get the unit of [`performance_time`] to be displayed following a
        /// measured value.
        ///
        /// # Examples
        ///
        /// ```rust,ignore
        /// impl<A> constance_test_suite::kernel_benchmarks::Driver<A> for Driver {
        ///     /* ... */
        ///     fn performance_time() -> u32 {
        ///         winapi::um::sysinfoapi::GetTickCount()
        ///     }
        ///     const PERFORMANCE_TIME_UNIT: &'static str = "ms";
        /// }
        /// ```
        const PERFORMANCE_TIME_UNIT: &'static str;

        /// The list of interrupt lines that can be used by test programs.
        ///
        ///  - The list can have an arbitrary number of elements. Some tests
        ///    will be silently skipped if it's not enough. There should be at
        ///    least two for all test cases to run.
        ///
        ///  - There must be no duplicates.
        ///
        ///  - The port must support [`enable_interrupt_line`],
        ///    [`disable_interrupt_line`], [`pend_interrupt_line`] for all of
        ///    the specified interrupt lines.
        ///
        /// [`enable_interrupt_line`]: constance::kernel::PortInterrupts::enable_interrupt_line
        /// [`disable_interrupt_line`]: constance::kernel::PortInterrupts::disable_interrupt_line
        /// [`pend_interrupt_line`]: constance::kernel::PortInterrupts::pend_interrupt_line
        const INTERRUPT_LINES: &'static [InterruptNum] = &[];

        /// A low priority value.
        ///
        /// Ignored if `INTERRUPT_LINES` is empty.
        ///
        /// Must be in range [`MANAGED_INTERRUPT_PRIORITY_RANGE`]
        ///
        /// [`MANAGED_INTERRUPT_PRIORITY_RANGE`]: constance::kernel::PortInterrupts::MANAGED_INTERRUPT_PRIORITY_RANGE
        const INTERRUPT_PRIORITY_LOW: InterruptPriority = 0;
        /// A high priority value.
        ///
        /// Ignored if `INTERRUPT_LINES` is empty.
        ///
        /// Must be in range [`MANAGED_INTERRUPT_PRIORITY_RANGE`]
        ///
        /// [`MANAGED_INTERRUPT_PRIORITY_RANGE`]: constance::kernel::PortInterrupts::MANAGED_INTERRUPT_PRIORITY_RANGE
        const INTERRUPT_PRIORITY_HIGH: InterruptPriority = 0;
    }

    /// The interface provided by [`use_benchmark_in_kernel_benchmark!`] and
    /// consumed by an inner app.
    trait Bencher<App> {
        /// Get a reference to `App` of the inner app.
        fn app() -> &'static App;

        fn mark_start();
        fn mark_end(int: crate::utils::benchmark::Interval);
    }

    /// Define an `App` type using [the benchmark
    /// framework](crate::utils::benchmark).
    ///
    /// `struct $inner_ty<System>` should be defined in the same module.
    /// `$inner_ty<System>` should have the following methods:
    ///
    ///  - `const fn new<B: crate::kernel_benchmarks::Bencher<Self>>(b: &mut
    ///    CfgBuilder<System>) -> Self`
    ///  - `fn iter<B: crate::kernel_benchmarks::Bencher<Self>>()`
    ///
    /// # Safety
    ///
    /// See [`crate::utils::benchmark::BencherOptions`].
    ///
    macro_rules! use_benchmark_in_kernel_benchmark {
        {
            pub unsafe struct App<System> {
                inner: $inner_ty:ident<System>,
            }
        } => {
            use crate::kernel_benchmarks::Driver;
            use crate::utils::benchmark;

            pub struct App<System> {
                benchmark: benchmark::BencherCottage<System>,
                inner: $inner_ty<System>,
            }

            struct MyBencherOptions<System, D>(core::marker::PhantomData<(System, D)>);

            impl<System: constance::kernel::Kernel> App<System> {
                pub const fn new<D: Driver<Self>>(
                    b: &mut constance::kernel::cfg::CfgBuilder<System>,
                ) -> Self {
                    App {
                        benchmark: benchmark::configure::<System, MyBencherOptions<System, D>>(b),
                        inner: $inner_ty::new::<MyBencherOptions<System, D>>(b),
                    }
                }
            }

            /// benchmark framework → app
            unsafe impl<System: constance::kernel::Kernel, D: Driver<App<System>>>
                benchmark::BencherOptions<System> for MyBencherOptions<System, D>
            {
                fn cottage() -> &'static benchmark::BencherCottage<System> {
                    &D::app().benchmark
                }

                fn iter() {
                    $inner_ty::iter::<MyBencherOptions<System, D>>();
                }

                fn performance_time() -> u32 {
                    D::performance_time()
                }

                const PERFORMANCE_TIME_UNIT: &'static str = D::PERFORMANCE_TIME_UNIT;

                fn finish() {
                    D::success()
                }
            }

            /// app → benchmark framework
            impl<System: constance::kernel::Kernel, D: Driver<App<System>>>
                crate::kernel_benchmarks::Bencher<$inner_ty<System>> for MyBencherOptions<System, D>
            {
                fn app() -> &'static $inner_ty<System> {
                    &D::app().inner
                }

                fn mark_start() {
                    <Self as benchmark::Bencher<System>>::mark_start()
                }
                fn mark_end(int: benchmark::Interval) {
                    <Self as benchmark::Bencher<System>>::mark_end(int)
                }
            }
        };
    }

    macro_rules! define_kernel_benchmarks {
        (
            [$dollar:tt] // get a `$` token
            $(
                // Test case definition
                (mod $name_ident:ident {}, $name_str:literal)
            ),*$(,)*
        ) => {
            $(
                /// [**Test Case**]
                #[cfg(any(
                    feature = "tests_all",
                    all(feature = "tests_selective", kernel_benchmark = $name_str)
                ))]
                pub mod $name_ident;
            )*

            /// The names of kernel benchmark tests.
            pub const TEST_NAMES: &[&str] = &[
                $( $name_str ),*
            ];

            /// Invoke the specified macro with a description of all defined
            /// kernel benchmark test cases.
            ///
            /// Note that the tests might not be actually compiled unless the
            /// feature `tests_all` is enabled.
            ///
            /// # Example
            ///
            /// ```rust,ignore
            /// constance_test_suite::get_kernel_benchmarks!(aaa::bbb!(prefix));
            /// ```
            ///
            /// This expands to something like this:
            ///
            /// ```rust,ignore
            /// aaa::bbb!(
            ///     prefix
            ///     { path: constance_test_suite::test1, name_ident: test1, name_str: "test1", },
            ///     { path: constance_test_suite::test2, name_ident: test2, name_str: "test2", },
            /// );
            /// ```
            ///
            #[macro_export]
            macro_rules! get_kernel_benchmarks {
                (
                    // Callback macro
                    $path:ident$dollar(::$path_sub:ident)* ! (
                        // Prefix of the callback parameter
                        $dollar($prefix:tt)*
                    )
                ) => {
                    $path$dollar($path_sub)* ! (
                        // Prefix
                        $dollar($prefix)*
                        $(
                            // The test info
                            {
                                path: $crate::kernel_benchmarks::$name_ident,
                                name_ident: $name_ident,
                                name_str: $name_str,
                            },
                        )*
                    );
                };
            }
        };
    }

    define_kernel_benchmarks! {
        [$]
        (mod cpu_analysis_int {}, "cpu_analysis_int"),
        (mod cpu_analysis_load {}, "cpu_analysis_load"),
        (mod task_lifecycle {}, "task_lifecycle"),
    }

    /// Invoke the specified macro with a description of test cases
    /// selected by `CONSTANCE_TEST`.
    ///
    /// Note that the tests might not be actually compiled unless the
    /// feature `tests_selective` is enabled.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// constance_test_suite::get_selected_kernel_benchmarks!(aaa::bbb!(prefix));
    /// ```
    ///
    /// If there's an environment variable `CONSTANCE_TEST=kernel_benchmark::test1`,
    /// this expands to:
    ///
    /// ```rust,ignore
    /// aaa::bbb!(
    ///     prefix
    ///     { path: constance_test_suite::test1, name_ident: test1, name_str: "test1", },
    /// );
    /// ```
    ///
    #[macro_export]
    macro_rules! get_selected_kernel_benchmarks {
        (
            // Callback macro
            $path:ident$(::$path_sub:ident)* ! (
                // Prefix of the callback parameter
                $($prefix:tt)*
            )
        ) => {
            // Forward to `get_selected_kernel_benchmarks_inner!`
            $crate::get_selected_kernel_benchmarks_inner!(
                ( $path $(::$path_sub)* ), ( $($prefix)* )
            );
        };
    }
}
